package kr.musicofcity.alginate;

import android.Manifest; import android.content.*; import android.content.pm.PackageManager; import android.graphics.Color; import android.net.Uri; import android.os.*; import android.provider.MediaStore; import android.view.*; import android.widget.*;
import androidx.activity.ComponentActivity; import androidx.activity.result.*; import androidx.activity.result.contract.ActivityResultContracts; import androidx.annotation.NonNull; import androidx.camera.core.*; import androidx.camera.lifecycle.ProcessCameraProvider; import androidx.camera.view.PreviewView; import androidx.core.content.ContextCompat;
import com.google.common.util.concurrent.ListenableFuture; import java.io.*; import java.nio.*; import java.nio.charset.StandardCharsets; import java.text.SimpleDateFormat; import java.util.*; import java.util.concurrent.*;

public class MainActivity extends ComponentActivity {
 static final int BG=Color.rgb(11,16,22),CARD=Color.rgb(18,26,36),TXT=Color.rgb(238,245,255),MUTED=Color.rgb(158,176,196),GREEN=Color.rgb(99,216,157);
 PreviewView preview; TextView status,rT,gT,bT,aT,cT,countT; Spinner channel; EditText ph,stdC,maxC,interval; Button autoBtn; ExecutorService ex; ProcessCameraProvider provider; Handler h=new Handler(Looper.getMainLooper()); volatile Reading cur; double blank=Double.NaN,k=Double.NaN; long start=0,lastFrame=0; boolean auto=false; final List<Row> rows=new ArrayList<>();
 final ActivityResultLauncher<String> perm=registerForActivityResult(new ActivityResultContracts.RequestPermission(),ok->{if(ok)startCamera();else status.setText("카메라 권한이 필요합니다.");});
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);setContentView(ui());ex=Executors.newSingleThreadExecutor();if(ContextCompat.checkSelfPermission(this,Manifest.permission.CAMERA)==PackageManager.PERMISSION_GRANTED)startCamera();else perm.launch(Manifest.permission.CAMERA);}
 View ui(){ScrollView s=new ScrollView(this);s.setBackgroundColor(BG);LinearLayout root=col();root.setPadding(d(14),d(14),d(14),d(30));s.addView(root);root.addView(txt("알긴산 비드 실시간 색도계",22,true));root.addView(txt("Galaxy S25 Edge · 후면카메라 중앙 ROI 실시간 분석",12,false));FrameLayout f=new FrameLayout(this);LinearLayout.LayoutParams fp=new LinearLayout.LayoutParams(-1,d(410));fp.setMargins(0,d(12),0,0);root.addView(f,fp);preview=new PreviewView(this);preview.setScaleType(PreviewView.ScaleType.FILL_CENTER);f.addView(preview,new FrameLayout.LayoutParams(-1,-1));View roi=new View(this);android.graphics.drawable.GradientDrawable rg=new android.graphics.drawable.GradientDrawable();rg.setColor(0x10000000);rg.setStroke(d(3),GREEN);rg.setCornerRadius(d(10));roi.setBackground(rg);f.addView(roi,new FrameLayout.LayoutParams(d(150),d(150),Gravity.CENTER));status=txt("카메라 준비 중",13,false);panel(status);root.addView(status,top(10));LinearLayout m1=row();rT=metric(m1,"R");gT=metric(m1,"G");bT=metric(m1,"B");root.addView(m1,top(8));LinearLayout m2=row();aT=metric(m2,"흡광도 A");cT=metric(m2,"농도");countT=metric(m2,"기록 수");root.addView(m2,top(8));LinearLayout p=col();panel(p);root.addView(p,top(10));channel=new Spinner(this);channel.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"R · 청색 색소 권장","G","B","밝기 L"}));p.addView(channel);LinearLayout x1=row();ph=edit("pH","7.0");interval=edit("기록 간격(초)","5");weight(x1,ph);weight(x1,interval);p.addView(x1);LinearLayout x2=row();stdC=edit("표준 농도","1.0");maxC=edit("100% 용출 농도","0");weight(x2,stdC);weight(x2,maxC);p.addView(x2);Button bb=btn("1. Blank 저장"),sb=btn("2. 표준용액 보정");LinearLayout q1=row();weight(q1,bb);weight(q1,sb);p.addView(q1);Button one=btn("현재 값 기록");autoBtn=btn("자동 기록 시작");LinearLayout q2=row();weight(q2,one);weight(q2,autoBtn);p.addView(q2);Button csv=btn("CSV 저장");Button reset=btn("기록 초기화");LinearLayout q3=row();weight(q3,csv);weight(q3,reset);root.addView(q3,top(10));root.addView(txt("측정 순서: Blank → 표준용액 → 시료 → 자동 기록. 조명·거리·용기·배경을 고정하세요.",12,false),top(10));bb.setOnClickListener(v->blank());sb.setOnClickListener(v->standard());one.setOnClickListener(v->record());autoBtn.setOnClickListener(v->toggle());csv.setOnClickListener(v->csv());reset.setOnClickListener(v->reset());channel.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){int last=0;public void onItemSelected(AdapterView<?>a,View v,int pos,long id){if(pos!=last){last=pos;blank=Double.NaN;k=Double.NaN;status.setText("채널 변경: Blank/표준 보정을 다시 하세요.");}}public void onNothingSelected(AdapterView<?>a){}});return s;}
 void startCamera(){status.setText("후면카메라 시작 중...");ListenableFuture<ProcessCameraProvider> f=ProcessCameraProvider.getInstance(this);f.addListener(()->{try{provider=f.get();Preview pr=new Preview.Builder().build();pr.setSurfaceProvider(preview.getSurfaceProvider());ImageAnalysis an=new ImageAnalysis.Builder().setBackpressureStrategy(ImageAnalysis.STRATEGY_KEEP_ONLY_LATEST).build();an.setAnalyzer(ex,this::analyze);provider.unbindAll();provider.bindToLifecycle(this,CameraSelector.DEFAULT_BACK_CAMERA,pr,an);status.setText("카메라 연결 완료. Blank를 ROI에 맞추세요.");}catch(Exception e){status.setText("카메라 오류: "+e.getMessage());}},ContextCompat.getMainExecutor(this));}
 void analyze(@NonNull ImageProxy im){try{long now=SystemClock.elapsedRealtime();if(now-lastFrame<250)return;lastFrame=now;ImageProxy.PlaneProxy[] ps=im.getPlanes();if(ps.length<3)return;int w=im.getWidth(),hh=im.getHeight(),sz=(int)(Math.min(w,hh)*.28),sx=(w-sz)/2,sy=(hh-sz)/2,step=Math.max(2,sz/70);ByteBuffer yb=ps[0].getBuffer(),ub=ps[1].getBuffer(),vb=ps[2].getBuffer();int yrs=ps[0].getRowStride(),yps=ps[0].getPixelStride(),urs=ps[1].getRowStride(),ups=ps[1].getPixelStride(),vrs=ps[2].getRowStride(),vps=ps[2].getPixelStride();long sr=0,sg=0,sb=0;int n=0;for(int y=sy;y<sy+sz;y+=step)for(int x=sx;x<sx+sz;x+=step){int yi=y*yrs+x*yps,ux=x/2,uy=y/2,ui=uy*urs+ux*ups,vi=uy*vrs+ux*vps;if(yi>=yb.limit()||ui>=ub.limit()||vi>=vb.limit())continue;int Y=yb.get(yi)&255,U=ub.get(ui)&255,V=vb.get(vi)&255,c=Math.max(0,Y-16),dd=U-128,e=V-128,R=cl((298*c+409*e+128)>>8),G=cl((298*c-100*dd-208*e+128)>>8),B=cl((298*c+516*dd+128)>>8);sr+=R;sg+=G;sb+=B;n++;}if(n==0)return;double R=sr/(double)n,G=sg/(double)n,B=sb/(double)n,I=switch(channel.getSelectedItemPosition()){case 0->R;case 1->G;case 2->B;default->.2126*R+.7152*G+.0722*B;};double A=Double.NaN,C=Double.NaN,rel=Double.NaN;if(!Double.isNaN(blank)&&blank>0&&I>0){A=-Math.log10(I/blank);if(!Double.isNaN(k)&&k>0){C=Math.max(0,A/k);double mx=num(maxC,0);if(mx>0)rel=C/mx*100;}}cur=new Reading(R,G,B,I,A,C,rel);Reading z=cur;runOnUiThread(()->show(z));}finally{im.close();}}
 void show(Reading z){rT.setText(f(z.r));gT.setText(f(z.g));bT.setText(f(z.b));aT.setText(Double.isNaN(z.a)?"-":String.format(Locale.US,"%.4f",z.a));cT.setText(Double.isNaN(z.c)?"-":String.format(Locale.US,"%.4f",z.c));}
 void blank(){if(cur==null){toast("측정값이 없습니다.");return;}blank=cur.i;k=Double.NaN;status.setText(String.format(Locale.US,"Blank 저장 완료 · I₀=%.2f",blank));}
 void standard(){if(cur==null||Double.isNaN(blank)){toast("먼저 Blank를 저장하세요.");return;}double sc=num(stdC,0),A=-Math.log10(cur.i/blank);if(!(sc>0&&A>0)){toast("표준용액 조건을 확인하세요.");return;}k=A/sc;status.setText(String.format(Locale.US,"표준 보정 완료 · k=%.5f",k));}
 void toggle(){if(auto){auto=false;h.removeCallbacks(autoRun);autoBtn.setText("자동 기록 시작");status.setText("자동 기록 중지");return;}auto=true;start=SystemClock.elapsedRealtime();autoBtn.setText("자동 기록 중지");record();h.postDelayed(autoRun,(long)(Math.max(1,num(interval,5))*1000));}
 final Runnable autoRun=new Runnable(){public void run(){if(!auto)return;record();h.postDelayed(this,(long)(Math.max(1,num(interval,5))*1000));}};
 void record(){if(cur==null){toast("측정값이 없습니다.");return;}if(start==0)start=SystemClock.elapsedRealtime();rows.add(new Row((SystemClock.elapsedRealtime()-start)/60000.0,num(ph,Double.NaN),cur));countT.setText(String.valueOf(rows.size()));}
 void reset(){auto=false;h.removeCallbacks(autoRun);autoBtn.setText("자동 기록 시작");rows.clear();start=0;countT.setText("0");status.setText("기록 초기화 완료. 보정값은 유지됩니다.");}
 void csv(){if(rows.isEmpty()){toast("저장할 데이터가 없습니다.");return;}String name="alginate_"+new SimpleDateFormat("yyyyMMdd_HHmmss",Locale.US).format(new Date())+".csv";ContentValues v=new ContentValues();v.put(MediaStore.Downloads.DISPLAY_NAME,name);v.put(MediaStore.Downloads.MIME_TYPE,"text/csv");v.put(MediaStore.Downloads.RELATIVE_PATH,Environment.DIRECTORY_DOWNLOADS+"/AlginateColorimeter");Uri u=getContentResolver().insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI,v);if(u==null){toast("CSV 생성 실패");return;}StringBuilder s=new StringBuilder("No,Time_min,pH,R,G,B,Absorbance,Concentration,Release_percent\n");for(int i=0;i<rows.size();i++){Row r=rows.get(i);s.append(i+1).append(',').append(String.format(Locale.US,"%.4f",r.t)).append(',').append(Double.isNaN(r.ph)?"":String.format(Locale.US,"%.2f",r.ph)).append(',').append(String.format(Locale.US,"%.3f,%.3f,%.3f,",r.r,r.g,r.b)).append(Double.isNaN(r.a)?"":String.format(Locale.US,"%.6f",r.a)).append(',').append(Double.isNaN(r.c)?"":String.format(Locale.US,"%.6f",r.c)).append(',').append(Double.isNaN(r.rel)?"":String.format(Locale.US,"%.3f",r.rel)).append('\n');}try(OutputStream o=getContentResolver().openOutputStream(u)){o.write(new byte[]{(byte)0xEF,(byte)0xBB,(byte)0xBF});o.write(s.toString().getBytes(StandardCharsets.UTF_8));toast("Downloads/AlginateColorimeter 저장 완료");}catch(Exception e){toast("CSV 오류: "+e.getMessage());}}
 LinearLayout col(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);return l;}TextView txt(String s,float z,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(bold?TXT:MUTED);if(bold)t.setTypeface(null,1);return t;}void panel(View v){android.graphics.drawable.GradientDrawable g=new android.graphics.drawable.GradientDrawable();g.setColor(CARD);g.setCornerRadius(d(14));v.setBackground(g);v.setPadding(d(10),d(10),d(10),d(10));}TextView metric(LinearLayout r,String name){LinearLayout b=col();panel(b);b.addView(txt(name,11,false));TextView v=txt("-",21,true);b.addView(v);weight(r,b);return v;}EditText edit(String hint,String val){EditText e=new EditText(this);e.setHint(hint);e.setText(val);e.setTextColor(TXT);e.setHintTextColor(MUTED);e.setInputType(android.text.InputType.TYPE_CLASS_NUMBER|android.text.InputType.TYPE_NUMBER_FLAG_DECIMAL);return e;}Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);return b;}void weight(LinearLayout p,View v){LinearLayout.LayoutParams q=new LinearLayout.LayoutParams(0,-2,1);q.setMargins(d(3),d(4),d(3),d(4));p.addView(v,q);}LinearLayout.LayoutParams top(int x){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,d(x),0,0);return p;}int d(int x){return(int)(x*getResources().getDisplayMetrics().density+.5f);}double num(EditText e,double x){try{return Double.parseDouble(e.getText().toString());}catch(Exception q){return x;}}String f(double x){return String.format(Locale.US,"%.1f",x);}static int cl(int x){return Math.max(0,Math.min(255,x));}void toast(String x){Toast.makeText(this,x,Toast.LENGTH_SHORT).show();}
 @Override protected void onDestroy(){super.onDestroy();auto=false;h.removeCallbacksAndMessages(null);if(provider!=null)provider.unbindAll();if(ex!=null)ex.shutdown();}
 static class Reading{final double r,g,b,i,a,c,rel;Reading(double r,double g,double b,double i,double a,double c,double rel){this.r=r;this.g=g;this.b=b;this.i=i;this.a=a;this.c=c;this.rel=rel;}}
 static class Row{final double t,ph,r,g,b,a,c,rel;Row(double t,double ph,Reading x){this.t=t;this.ph=ph;r=x.r;g=x.g;b=x.b;a=x.a;c=x.c;rel=x.rel;}}
}
